# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-28 19:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='domainHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentOwner', models.CharField(max_length=200)),
                ('previousOwner', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='listedTransfers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller', models.CharField(max_length=200)),
                ('buyer', models.CharField(max_length=200)),
                ('domain', models.CharField(max_length=200)),
                ('status', models.BooleanField(default=False)),
                ('ts', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='domainhistory',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.listedTransfers'),
        ),
    ]
