# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-20 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_domainhistory_previousowner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domainhistory',
            name='domain',
        ),
        migrations.RemoveField(
            model_name='listedtransfers',
            name='status',
        ),
        migrations.AddField(
            model_name='listedtransfers',
            name='amount',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listedtransfers',
            name='payeemobile',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listedtransfers',
            name='payeeva',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listedtransfers',
            name='payermobile',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listedtransfers',
            name='payerva',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listedtransfers',
            name='selleraccount',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='domainHistory',
        ),
    ]
