# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-20 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190320_0758'),
    ]

    operations = [
        migrations.AddField(
            model_name='listedtransfers',
            name='state',
            field=models.BooleanField(default=False),
        ),
    ]
